### ISSUE TITLE
Large cpu consumption

### ISSUE THREAD

**Issue by renarios** [siom79/jdrivesync#1]
Hi Martin,

jdrivesync does the job well, but it is quite slow. 
I just used jdrivesync to synchronise a 22MB file to my Google drive, but it takes ages to upload:
It took 2082690 ms for 22566928 bytes: 10.59 KB/s with one core at 100% all the time. Is there a way to speed it up?

**Comment by siom79** [comment]
jdrivesync internally uses Google's Drive SDK. This implementation is a bit slow (see this issue [here](https://github.com/google/google-http-java-client/issues/278)). One day, when I have enough time, I will replace this implementation with a faster one.

**Comment by siom79** [comment]
Today I have reworked the upload implementation and released it as version [0.2.2](https://github.com/siom79/jdrivesync/releases/tag/jdrivesync-0.2.2). On my machine this version was a lot faster than the previous one. Please let me know if it does the job better on your machine.

**Comment by renarios** [comment]
Thanks Martin, it performs a lot better now at 522.50 KB/s. That's really acceptable. Thanks!
