### ISSUE TITLE
Cannot download Google app document

### ISSUE THREAD

**Issue by linhpha** [siom79/jdrivesync#18]
When I ran the program, it ignores all the Google app documents and not download them to local folder. Is this part of the design decision? I suppose that the app is using Google Drive v2, which seems to not have the export function like v3 to download Google App documents. Is the developer team intending to add this function in the future?

**Comment by siom79** [comment]
Hello Linh,

jdrivesync uses the v2 API, as you have already guessed. If I find some
time in the near future and I am willing to port the application to v3.
Then it should be possible to export Google Drive documents.

Best Regards
Martin Mois

Linh Pham <notifications@github.com> schrieb am Fr., 28. Juli 2017, 21:21:
