### ISSUE TITLE
Build instructions are missing

### ISSUE THREAD

**Issue by proski** [siom79/jdrivesync#4]
There should be an instruction how to build jdrivesync from source. It may be obvious for Java developers, but not for every "grive refugee" who wants to try the latest code and possibly contribute a patch or two. Please specify what versions of maven are needed, how to run them to compile and install the program, how to make a Debian package. Let's start with something basic, and somebody would contribute instructions how to build an rpm or maybe compile the package natively.

**Comment by siom79** [comment]
I have added some basic instructions on how to contribute to the `README.md` on the develop branch (see [here](https://github.com/siom79/jdrivesync/tree/develop#development)). Let me know if this is sufficient to get you started.

**Comment by proski** [comment]
Very nice document, thank you! But it requires maven 3.2 or newer. I'm using Ubuntu 15.04 and it doesn't have maven 3.2. It have package `maven` that is version 3.0.5 and maven2 that is version 2.2.1. Either version of maven can build the project. So I think the requirement for maven version could be relaxed to 2.2.1.

**Comment by siom79** [comment]
Nice to hear that the build is compatible with maven 2.2.1, but as this version is nearly six years old and maven 2.x is considered to have reached its end of life (see [here](https://maven.apache.org/docs/history.html)), I don't want to officially support that. 

On the other hand the "installation" of maven is such easy, that you do not need to use a deb package. Just download the tarball, extract it and set one environment variable (see [here](https://maven.apache.org/download.cgi#Installation)).
