### ISSUE TITLE
Ignore folder

### ISSUE THREAD

**Issue by compyy** [siom79/jdrivesync#9]
Hi, 

There should be an option to ignore directory, seems like -i is not helping with regular expression.

As example:
sudo java -jar jdrivesync.jar --dry-run -l "/home/yasir/Google" -i /home/yasir/Google/Documents/**
Could not read file '/home/yasir/Google/Documents/Budget':Is a directory

udo java -jar jdrivesync.jar --dry-run -l "/home/yasir/Google" -i "/home/yasir/Google/Documents/Budget/_"
'/home/yasir/Google/Documents/Budget/_' does not exist.

**Comment by siom79** [comment]
Hello compyy,

the option `-i` expects a file that contains file or directory patterns, one pattern per line. So please try to create a file (for example jdrivesync.txt) and then pass the file location using the `-i` option:

```
java -jar jdrivesync.jar -i "/path/to/jdrivesync.txt" ...
```

**Comment by compyy** [comment]
Hi,

Thanks, but help doesnt mention as you are telling me here, i will try but you need to update the help as well.

Thanks.

**Comment by siom79** [comment]
Hi,

the option actually mentions that it expects an file:

```
-i,--ignore-file <ignore-file>
        Provides a file with newline separated file and/or path name patterns that should be ignored.
```
